### ISSUE TITLE
optparse-applicative dependency needs a version constraint

### ISSUE THREAD

**Issue by Quix0r** [mithrandi/ssh-key-generator#1]
Building the main program fails:

[1 of 1] Compiling Main             ( app/KeyTool.hs, dist/build/ssh-key-generator/ssh-key-generator-tmp/Main.o )

app/KeyTool.hs:8:39:
    Module `Options.Applicative' does not export`eitherReader'

app/KeyTool.hs:8:108:
    Module `Options.Applicative' does not export`ReadM'

**Comment by mithrandi** [comment]
It seems like you have a version of optparse-applicative which is too old; my .cabal file does not specify any version bound, so correcting this should solve your problem, but I'm not actually sure in what version `eitherReader` and `ReadM` were first exported.

Could you check which version of optparse-applicative you have? If you are using a cabal sandbox as suggested by the README, you can paste the output of `cabal sandbox hc-pkg list optparse-applicative`; otherwise if you're not using a sandbox, `ghc-pkg list optparse-applicative` is what you want.

**Comment by mithrandi** [comment]
Okay, in the meanwhile, I tracked down the correct version, so this should be fixed. Could you try again? It'll probably be easiest to just run `cabal sandbox delete` before starting again.
